name: Read milestone file
author: mmagician
description: 'Read file contents'
inputs:
  path:
    description: 'File path'
    required: true
outputs:
  application_document:
    description: 'Link to application PR'
  milestone_number:
    description: 'Milestone number'
  is_maintenance:
    description: 'True IFF the delivery is for a maintenance grant'
runs:
  using: 'node12'
  main: 'dist/index.js'
